### ISSUE TITLE
ERROR: --enable_cuda=True :: Unrecognized option: --enable_cuda=True

### ISSUE THREAD

**Issue by LinGeLin** [bazel-contrib/rules_cuda#102]
ERROR: --enable_cuda=True :: Unrecognized option: --enable_cuda=True

got error when build example if_cuda with `bazel build //if_cuda_main`

why?

**Comment by cloudhan** [comment]
`//if_cuda_main` is not correct label.

**Comment by LinGeLin** [comment]
rules_cuda/examples# bazel build //if_cuda:main
INFO: Reading rc options for 'build' from rules_cuda/examples/.bazelrc:
  'build' options: --flag_alias=enable_cuda=@rules_cuda//cuda:enable --flag_alias=cuda_archs=@rules_cuda//cuda:archs --flag_alias=cuda_compiler=@rules_cuda//cuda:compiler --flag_alias=cuda_copts=@rules_cuda//cuda:copts --flag_alias=cuda_runtime=@rules_cuda//cuda:runtime --enable_cuda=True --ui_event_filters=-INFO
ERROR: --enable_cuda=True :: Unrecognized option: --enable_cuda=True

**Comment by LinGeLin** [comment]
Why are you in such a hurry to close? I just made a spelling mistake when I submitted the issue, but I made a mistake when I actually executed the command. @cloudhan
