### ISSUE TITLE
INCLUDE env_entry is not allowed to be empty 

### ISSUE THREAD

**Issue by cloudhan** [bazel-contrib/rules_cuda#111]
From an unknown timepoint, the windows CI starts to fail with 

```
ERROR: C:/users/runneradmin/_bazel_runneradmin/gmezm5mc/external/local_cuda/toolchain/BUILD:20:[22](https://github.com/bazel-contrib/rules_cuda/actions/runs/5158430370/jobs/9292103159#step:6:23): in cuda_toolchain_config rule @local_cuda//toolchain:nvcc-local-config: 
Traceback (most recent call last):
	File "D:/a/rules_cuda/rules_cuda/cuda/private/toolchain_configs/nvcc_msvc.bzl", line 56, column [30](https://github.com/bazel-contrib/rules_cuda/actions/runs/5158430370/jobs/9292103159#step:6:31), in _impl
		env_entry("INCLUDE", ";".join(cc_toolchain.built_in_include_directories)),
	File "C:/users/runneradmin/_bazel_runneradmin/gmezm5mc/external/bazel_tools/tools/cpp/cc_toolchain_config_lib.bzl", line 65, column 30, in env_entry
		_check_is_nonempty_string(value, "value", "env_entry")
	File "C:/users/runneradmin/_bazel_runneradmin/gmezm5mc/external/bazel_tools/tools/cpp/cc_toolchain_config_lib.bzl", line 37, column 13, in _check_is_nonempty_string
		fail("{} parameter of {} must be a nonempty string."
Error in fail: value parameter of env_entry must be a nonempty string.
ERROR: C:/users/runneradmin/_bazel_runneradmin/gmezm5mc/external/local_cuda/toolchain/BUILD:20:22: Analysis of target '@local_cuda//toolchain:nvcc-local-config' failed
ERROR: Analysis of target '//tests/flag:cuda_library_c_fastbuild_static_msvcrt_flag_test' failed; build aborted:
```

It seems that the CI environment is changed in upstream and is undocumented. An workaround is desired.

**Comment by psv4** [comment]
Was the change between `windows-latest` and `windows-2019` determined? I am experiencing this issue on my local Windows workstation and looking for a fix.

**Comment by cloudhan** [comment]
@psv4 This is not a cuda rules problem, and not even bazel cc_rules problem. visual c installation folder structure changed at some point of a release, some old versions of bazel cannot detect the installation for the new folder structure. We need to test this rule back up to oldest LTS release of bazel, so we held back the image version for this reason.

If you need to use old version bazel, then use vs 2019 or better update your bazel to 6.4 (if not 7

**Comment by psv4** [comment]
@cloudhan, thanks for the response. Tested that 6.4 still had the issue, but 6.5 and 7.0 were able to find VS 2022 correctly.
