### ISSUE TITLE
`-c fastbuild` defaults to -O3, `-c opt` defaults to -O2

### ISSUE THREAD

**Issue by siboehm** [bazel-contrib/rules_cuda#128]
I may be mistaken, but in the default `-c fastbuild` mode rules_cuda doesn't pass any -O flags to nvcc, and since [nvcc defaults to optimization level 3](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#opt-level-n-o) it'll be building with -O3.

For `-c opt` it passes -O2: https://github.com/bazel-contrib/rules_cuda/blob/039ee7bf59790e4d8e7c279d298f618ab5b3d2b5/cuda/private/toolchain_configs/nvcc.bzl#L317

so this looks like `-c opt` actually results in less optimization?

**Comment by cloudhan** [comment]
This behavior is mirrored from https://bazel.build/docs/user-manual?hl=en#compilation-mode

> `opt` means build with optimization enabled and with `assert()` calls disabled (`-O2 -DNDEBUG`).

But it seems for `fastbuild` that I missed
> and don't optimize

**Comment by cloudhan** [comment]
I not sure if the `-O0` will affect the opt level of device code or not. And I also cannot recall if it is the root cause of the absent of that flag. For me, the device code opt should always be enabled by default to avoid unexpected perf issue.

**Comment by cloudhan** [comment]
> I not sure if the -O0 will affect the opt level of device code or not.

https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#optimize-level-o, so it works for host code only, great.

But it should be carefull for clang:

https://github.com/llvm/llvm-project/blob/544b4c6d522fa78f65eb850160c0380a0100250d/clang/test/Driver/cuda-external-tools.cu#L31-L45

And https://reviews.llvm.org/D17111#349388

**Comment by siboehm** [comment]
I looked at this again:
1. It's not actually clear what the default optimization level (for host code) is. The [nvcc docs](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#optimize-level-o) do not specify a default, contrary to what my first message said. The link I posted earlier specified the default for ptxas.
2. The ptxas default setting is indeed -O3, see [here](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#opt-level-n-o). How about we follow clang here, and use -O0 in `dbg` and `fastbuild`?

**Comment by cloudhan** [comment]
@siboehm Also updated for nvcc for win. 

> The ptxas  ... and use -O0 in dbg and fastbuild

Disagree for now. `-Xptxas -O0` may make the compilation a bit faster. But also it may results in unuable binary due to heavily skew perf characteristics or not compilable due to too many template tricks.
