### ISSUE TITLE
Compilation parameter is not shared between rules_cc and rules_cuda

### ISSUE THREAD

**Issue by noaxp** [bazel-contrib/rules_cuda#136]
Hi, I'm searching bazel cuda solution for my group, we are using [TF rules_cuda](https://github.com/tensorflow/runtime/tree/master/third_party/rules_cuda) now.
I found TF's design is different with this repo. The general idea is making `cuda_library` just a macro wrapper of `cc_library`, [see the code](https://github.com/tensorflow/runtime/blob/master/third_party/rules_cuda/cuda/defs.bzl).

Then, TF `cuda_library` will share many compilation parameters and environment with `cc_library`, I thinks it's a good feature.
For example, when we set `cxxopt` to `-DENABLE_FEATURE=1` in bazelrc, `nvcc` will also get the parameter.
While `bazel-contrib/rules_cuda` requires to set `-DENABLE_FEATURE=1` for both `cxxopt` and `cuda_copt`. If we forget to do it for both c++ and cuda, the macro value will be inconsistent between c++ and cuda lib.

So I'm curious about the consideration in `rules_cuda` design.
1. About the interface design, do you think it's better to share config between `rules_cc` and `rules_cuda` just like TF `rules_cuda`?
2. About the implementation, which implementation do you like, write `rules_cuda` independent of `rules_cc`, or just wrap `rules_cc`?

Looking forward to your suggestion, and thank you for the great project!

**Comment by cloudhan** [comment]
> do you think it's better to share config between `rules_cc` and `rules_cuda`

No, I don't think so, it is even incorrect to do so. There are many flags that cannot be consumed by nvcc. TF is actually doing more than you think, for example, in https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/windows/msvc_wrapper_for_nvcc.py.tpl it is filter some flags and replacing the inproper ones to their correct form... Without doing so, unknown flags result in errors.

They are different languages and toolchains. You better configure them correspondingly. cmake also follow this practice.

cc_library compilation model does not fit into the CUDA world. It is single pass, then relocatable device code is not even achievable directly. Thus you cannot compile something like nccl. See this wrapper (AGAIN!) https://github.com/tensorflow/tensorflow/blob/3ccce977a0c92e3297176162ccedc50724d53c4f/third_party/nccl/build_defs.bzl.tpl#L265-L412

> which implementation do you like

Do you still like cc wrapper? ;)

This is not quite finished example https://github.com/bazel-contrib/rules_cuda/tree/cloudhan/nccl-example/examples/nccl.

**Comment by noaxp** [comment]
@cloudhan Appreciate for the detailed explanation, learn it a lot! I agree that the wrapper implementation is not a good idea.
Now, I decide to divide our c++ config into three components: cpp_only / cuda_only / cpp_cuda_shared.

**Comment by noaxp** [comment]
@ZhenshengLee Sure.
We maintain cpp compilation options in bazelrc. To keep consistent options between gcc/clang and nvcc, you could simply copy c/cpp options `--copt` and `--cxxopt` to `@rules_cuda//cuda:copts`. Nvcc couldn't recognize all the cpp options, so you need to use `--cuda_host_copts` for those options.

If you have a huge code base and many compilation options, you would worry about the maintainability. Someone may change the cpp compilation options and forget doing the same thing on cuda options. So it's better to split the options into three parts (e.g. three files), `cpp_only` for cpp compiler / `cuda_only` for nvcc / `cpp_cuda_shared` for both compiler. Then we could use script to generate the final cpp/cuda options, which would be imported to bazelrc.

In practice, I suggest to split cpp and cuda code into different compilation unit, then there won't be any shared compilation options, and you won't need to worry about the options problem. It's an important and critical decision, it'll be too complex to discuss here :)
