### ISSUE TITLE
Proposal to add a `cuda_test` rule

### ISSUE THREAD

**Issue by hofbi** [bazel-contrib/rules_cuda#166]
When using the `cc_test` rule, tests that are using cuda are compiled with `cc` compilers and not with `nvcc`. An easy solution for this is to provide a rule `cuda_test` that delegates everything to the `cuda_libary` and finally uses a `cc_test` depending on the cuda target. Something like 

```starlark
def cuda_test(name, srcs = [], ...):
    cuda_library_name = "_" + name

    cuda_library(
        name = cuda_library_name,
        srcs = srcs,
        ...
    )

    cc_test(
        name = name,
        deps = [cuda_library_name],
        ...
    )
```

**Comment by cloudhan** [comment]
I think it is generally good, contribution are welcomed.
