### ISSUE TITLE
Request: Cut a new release?

### ISSUE THREAD

**Issue by bgianfo** [bazel-contrib/rules_cuda#177]
Would it be possible to cut a new release soon? I would like to consume the `cuda_test(..)` functionality as part of an official release.

**Comment by cloudhan** [comment]
At the moment, you can use
```starlark
http_archive(
    name = "rules_cuda",
    sha256 = "442a9d15adb4615cd76748d0769d80a1f190b14ea0948de9777c997ddbf46ad8",
    strip_prefix = "rules_cuda-d3b9ab7d3af2040aa3bb007b66c224d7dc9af06b",
    urls = ["https://github.com/bazel-contrib/rules_cuda/archive/d3b9ab7d3af2040aa3bb007b66c224d7dc9af06b.tar.gz"],
)
```
to consume the main branch directly.

There will be a 0.2.1 release recently, but mainly for fixing #162.

**Comment by cloudhan** [comment]
v0.2.1 tagged. cuda_test included.
