### ISSUE TITLE
Bug: `cuda_test` doesn't support `size`, as you can't pass it to `cuda_library`. 

### ISSUE THREAD

**Issue by bgianfo** [bazel-contrib/rules_cuda#178]
Bazel tests accept a `size` argument, the new `cuda_test` macro doesn't support this because of how it's implemented. For example consider the following test case: 

```python
cuda_test(
    name = "test",
    srcs = ["test.cu"],
    # Size the test appropriately so it has enough time for the test to run.
    size = "enormous",
    deps = [ 
        ":assertions",
    ],  
)
```

If you attempt to pass `size`, hoping it gets push down to the internal `native.cc_test`, it will instead error out with the following message: 

```
package contains errors: tests: //tests:test: no such attribute 'size' in 'cuda_library' rule
```

**Comment by cloudhan** [comment]
It seems we should also filter all other attrs listed in https://bazel.build/reference/be/common-definitions?hl=en#common-attributes-tests
