### ISSUE TITLE
Add attribute `tags`

### ISSUE THREAD

**Issue by hofbi** [bazel-contrib/rules_cuda#179]
Many people might want to tag their cuda targets with `gpu` or something, hence it would be nice to add a `tags` attribute to `cuda_libary` and `cuda_object`

**Comment by cloudhan** [comment]
Do we need to manually added as an attribute? https://bazel.build/reference/be/common-definitions?hl=en#common-attributes claims it is common to all build rule, I am not sure does it apply to user defined rules or not.

**Comment by hofbi** [comment]
I expected that this should work by default but for some reason passing a tag does not work.

**Comment by ryanleary** [comment]
@hofbi do you have a repro for this? I'll confirm tomorrow, but I'm pretty sure we have cuda targets with tags in some of our projects working as expected.

**Comment by hofbi** [comment]
Sorry, nothing that I can share. Let me double check, maybe it works meanwhile.

**Comment by hofbi** [comment]
Looks like it is working now. We can close this one.
