### ISSUE TITLE
Custom cuda version usage

### ISSUE THREAD

**Issue by the-code-samurai-97** [bazel-contrib/rules_cuda#195]
My Laptop uses cuda 11.7 and i want to use Cuda 12 , Is there a way to use cuda 12.x without local installing can i download tar.gz using bazel

**Comment by cloudhan** [comment]
Sorry, I don't quite get you language. I am guessing that you want to extract the cuda toolkit to a non-standard path (that is, without instlalling), Then you can use call `rules_cuda_dependencies(toolkit_path="<your_custom_cuda_path>")` in your `WORKSPACE` file or you can use `--repo_env=CUDA_PATH=<your_custom_cuda_path>`

See https://github.com/bazel-contrib/rules_cuda/blob/5633f0c0f7/cuda/private/repositories.bzl#L31-L35

**Comment by sibi-venti** [comment]
can i download the cuda and compile using bazel?

**Comment by cloudhan** [comment]
@sibi-venti

 Previous method change where the `cuda_path` point to, then in https://github.com/bazel-contrib/rules_cuda/blob/1a2ec3d1ffacf3c462b69c2bbac91111d1752d21/cuda/private/repositories.bzl#L28-L82

`_get_nvcc_version` runs the nvcc to extract the version for your.

So the answer is yes and no. bazel does not compile, instead, it drives the compilation.

**Comment by cloudhan** [comment]
So by override the default cuda toolkit search path, and still relying the detecting machenism, you don't need do anything. Otherwise it should be treated as a bug.
