### ISSUE TITLE
Issue using rules as Bazel module with git override

### ISSUE THREAD

**Issue by hypdeb** [bazel-contrib/rules_cuda#199]
Hello,

I'm trying to use these rules as a Bazel module, but am failing. Here is a minimal reproduction:

`WORKSPACE`
```skylark
load("@rules_cuda//cuda:repositories.bzl", "register_detected_cuda_toolchains", "rules_cuda_dependencies")

rules_cuda_dependencies()

register_detected_cuda_toolchains()

```

`MODULE.bazel`
```
module(
    name = "test_rules_cuda",
    version = "1.0",
)

bazel_dep(name = "rules_cuda")

git_override(module_name = "rules_cuda", remote = "https://github.com/bazel-contrib/rules_cuda.git", commit = "1a2ec3d1ffacf3c462b69c2bbac91111d1752d21")

```

`BUILD`
```
load("@rules_cuda//cuda:defs.bzl", "cuda_library")

cuda_library(
    name = "demo",
    srcs = [
    ],
    hdrs = [
        "src.h",
    ],
    visibility = ["//visibility:public"],
)

```

It does not matter what is in the `src.h` as far as I can tell.

I'm using version `6.4.0` of Bazel and CUDA `12.2.0`, my `CUDA_PATH` is set in Ubuntu 22.04 running in the WSL.

I get the following error message:
`ERROR: Analysis of target '//:demo' failed; build aborted: module extension "toolchain" from "@rules_cuda~override//cuda:extensions.bzl" does not generate repository "local_cuda", yet it is imported as "local_cuda" in the usage at @@rules_cuda~override//:MODULE.bazel:10:26`

**Comment by cloudhan** [comment]
You need https://github.com/bazel-contrib/rules_cuda/blob/1a2ec3d1ffacf3c462b69c2bbac91111d1752d21/examples/MODULE.bazel#L13-L18
in your `MODULE.bazel`

**Comment by hypdeb** [comment]
That seems to work. I will need to read up to understand what this does though.
