### ISSUE TITLE
Question: Is cuda_library able to be used as input to cc_shared_library?

### ISSUE THREAD

**Issue by Ryang20718** [bazel-contrib/rules_cuda#200]
if I create a cuda_library and pass the target to a `cc_shared_library`, it seems that there's an error
`(rule 'cuda_library') doesn't contain declared provider 'GraphNodeInfo'`

**Comment by cloudhan** [comment]
IIRC, it could be used with the builtin cc_shared_library, like in [163](https://togithub.com/bazel-contrib/rules_cuda/issues/163), but is not tested for rules_cc.

**Comment by Ryang20718** [comment]
Hm.. I'm using `native.cc_shared_library`, but using a `cuda_library` as a dep. The error I get is the lack of GraphNodeInfo https://github.com/bazelbuild/bazel/blob/d9dc4fde4c8d06498f39b54a81d4e7fa1e5b5b30/src/main/starlark/builtins_bzl/common/cc/cc_shared_library.bzl#L33


An example to repro this issue. building lib_shared results in the error "doesn't contain declared provider GraphNodeInfo"

```
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 656, column 114, in _cc_shared_library_impl
        File "/virtual_builtins_bzl/common/cc/experimental_cc_shared_library.bzl", line 383, column 48, in _filter_inputs
        Error (rule 'cuda_library') doesn't contain declared provider 'GraphNodeInfo'
```


```
cuda_library(
    name = "vector_add",
    srcs = ["vector_add.cu"],
    visibility = ["//visibility:public"],
)

cc_shared_library(
    name = "lib_shared",
    deps = [":vector_add"],
)
```

vector_add.cu
```

#include <stdio.h>

#include <cuda_runtime.h>
#include <cuda.h>
#include <cuda_fp16.h>

#include <cudnn.h>
#include <curand_kernel.h>
#include <cublas_v2.h>

__global__ void
vector_add(const float *A, const float *B, float *C, int numElements)
{
    int i = blockDim.x * blockIdx.x + threadIdx.x;

    if (i < numElements)
    {
        C[i] = A[i] + B[i];
    }
}
```

**Comment by cloudhan** [comment]
It is pretty weird, I can compile liblib_shared.so with bazel 7.0, 6.3.2 and 6.2.1, So it might be a problem on your side.

What is the bazel version that you are using?

**Comment by Ryang20718** [comment]
ah we're using bazel 6.3.2. I wonder if there's something different with our setup. Trying to figure out what's different from our setup. Wondering if I'm missing something here 😅 


<details> 

<summary>Try to build the example in rules_cuda</summary>

I used the following steps:

- run a docker container
```
docker run --gpus 1 --env NVIDIA_DRIVER_CAPABILITIES=all -u root -v "/home/ryang/repos/testing_cuda":/home/github_actions/testing_cuda -it nvidia/cuda:12.0.1-cudnn8-runtime-ubuntu20.04 
```

- clone the rules_cuda repo

- set up cuda_path
```
root@0ed178a2f4cf:/home/github_actions/rules_cuda/examples# export CUDA_PATH=/usr/local/cuda
root@0ed178a2f4cf:/home/github_actions/rules_cuda/examples# which gcc
/usr/local/cuda/bin/gcc
root@0ed178a2f4cf:/home/github_actions/rules_cuda/examples# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

root@0ed178a2f4cf:/home/github_actions/rules_cuda/examples# ls /usr/local/cuda/
bin  compat  gds  include  lib64  nvidia-cuda-toolkit  targets
```

- bazel build simple example results in weird errors of missing files even though the file exists

```
root@0ed178a2f4cf:/home/github_actions/rules_cuda/examples# bazel build //basic:main --action_env=CC=/usr/bin/gcc
Starting local Bazel server and connecting to it...
ERROR: /home/github_actions/rules_cuda/examples/basic/BUILD.bazel:11:10: Linking basic/main failed: missing input file '@local_cuda//:cuda/lib64/libcudadevrt.a'
ERROR: /home/github_actions/rules_cuda/examples/basic/BUILD.bazel:11:10: Linking basic/main failed: 1 input file(s) do not exist
Target //basic:main failed to build

root@0ed178a2f4cf:/home/github_actions/rules_cuda/examples# ./bazel query @local_cuda//:* | grep libcudadevrt
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'query' from /home/github_actions/rules_cuda/examples/.bazelrc:
  Inherited 'common' options: --announce_rc
Loading: 0 packages loaded
@local_cuda//:cuda/lib64/libcudadevrt.a
```

</details>

**Comment by cloudhan** [comment]
The image you are using is cuda-12.0, but the nvcc is not included in the image, and from your log, your are using `10.1, V10.1.243`?

**Comment by Ryang20718** [comment]
🤦 🙇 

I appreciate you very much.

Issue was narrowed down to our macro.

**Comment by jsharpe** [comment]
> Hm.. I'm using `native.cc_shared_library`, but using a `cuda_library` as a dep. The error I get is the lack of GraphNodeInfo [bazelbuild/bazel@`d9dc4fd`/src/main/starlark/builtins_bzl/common/cc/cc_shared_library.bzl#L33](https://github.com/bazelbuild/bazel/blob/d9dc4fde4c8d06498f39b54a81d4e7fa1e5b5b30/src/main/starlark/builtins_bzl/common/cc/cc_shared_library.bzl#L33)
> 
> Wondering if I'm doing something wrong? 😓
> 

I'm running into exactly this issue - @Ryang20718 can you share what the issue was with your macro? I don't quite understand how that fixed things when your reproducer was also failing at analysis time which doesn't use any macros.

**Comment by Ryang20718** [comment]
original issue was that our macro was using a patched version of rules_cuda that was a couple of versions behind. @jsharpe are you on latest rules_cuda?
