### ISSUE TITLE
Untracked `MODULE.bazel.lock` files

### ISSUE THREAD

**Issue by rygx** [bazel-contrib/rules_cuda#223]
bzlmod will automatically generate `MODULE.bazel.lock` files, but this file is neither tracked by git nor placed in .gitignore file, causing every time git to alert `MODULE.bazel.lock` not being tracked, and adds to chance that this file is committed inadvertently. IMO it could be a quite simple fix by choosing either of the options:
- Option 1: check in `MODULE.bazel.lock` files, if we are sure that this file is consistent across different machines (theoretically the lock file should maintain consistent on different machines, but I am not sure if there are any non-hermetic factors would cause environment-dependent contents).
- Option 2: add `MODULE.bazel.lock` file into `.gitignore`, if we are unsure if the lock file would be consistent. 

I would be happy to provide PR if either of the above options is a way to move forward.

**Comment by cloudhan** [comment]
Let's opt for ignore the files. 

IIRC, I read through an github issue or discussion that mention it but cannot find it again. It mentions that the lock file is not quite stable at the moment, and needs some refine on it. So lets ignore it for now and keep an eye on it.

**Comment by rygx** [comment]
Sounds good to me. Created #224 

BTW, I saw github issue in bazel repo https://github.com/bazelbuild/bazel/issues/20369, not sure if that was what you saw.
