### ISSUE TITLE
unable to find libcudart.so in Conda

### ISSUE THREAD

**Issue by jrouly** [bazel-contrib/rules_cuda#233]
Hey folks!

I'm trying to build the [femr](https://github.com/som-shahlab/femr) package in a Conda environment. It uses Bazel for native C compilation, and in turn uses `rules_cuda` for its CUDA library support.

My Conda has the following key packages installed:
```
  cuda                     11.8.0       0                   nvidia/label/cuda-11.8.0
  cuda-cupti               11.8.87      0                   nvidia/label/cuda-11.8.0
  cuda-libraries-dev       11.8.0       0                   nvidia/label/cuda-11.8.0
  cuda-nvcc                11.8.89      0                   nvidia/label/cuda-11.8.0
  cuda-nvtx                11.8.86      0                   nvidia/label/cuda-11.8.0
  python                   3.10.13      hd12c33a_1_cpython  conda-forge             
```

I've got bazelisk installed globally outside of Conda.

When I run `bazelisk build` in the `femr/native` directory, I run into this perplexing error:

```
$ export LD_LIBRARY_PATH=/home/jovyan/micromamba/envs/cuda-11/lib/
$ bazelisk build -c dbg extension.so --//:cuda=enabled --verbose_failures
INFO: Analyzed target //:extension.so (0 packages loaded, 0 targets configured).
ERROR: /home/jovyan/.cache/bazel/_bazel_jovyan/d137f59fd319ac4509c40ee828786931/external/local_cuda/BUILD:42:10: SolibSymlink _solib_k8/_U@@local_Ucuda_S_S_Ccudart_Uso___Ucuda_Slib64/libcudart.so failed: missing input file '@@local_cuda//:cuda/lib64/libcudart.so'
ERROR: /home/jovyan/.cache/bazel/_bazel_jovyan/d137f59fd319ac4509c40ee828786931/external/local_cuda/BUILD:42:10: SolibSymlink _solib_k8/_U@@local_Ucuda_S_S_Ccudart_Uso___Ucuda_Slib64/libcudart.so failed: 1 input file(s) do not exist
Target //:extension.so failed to build
ERROR: /home/jovyan/.cache/bazel/_bazel_jovyan/d137f59fd319ac4509c40ee828786931/external/local_cuda/BUILD:42:10 SolibSymlink _solib_k8/_U@@local_Ucuda_S_S_Ccudart_Uso___Ucuda_Slib64/libcudart.so failed: 1 input file(s) do not exist
INFO: Elapsed time: 0.284s, Critical Path: 0.03s
INFO: 3 processes: 3 internal.
ERROR: Build did NOT complete successfully
```

The build succeeds when CUDA and Bazel are `apt-get install`'d, e.g. in a Dockerfile build environment. So it seems to be Conda that's introducing the inability to locate `libcudart.so`.

Not sure where to go from here!

**Comment by cloudhan** [comment]
See the toolkit detection logic: https://github.com/bazel-contrib/rules_cuda/blob/5633f0c0f7/cuda/private/repositories.bzl#L28-L58

Currently it might not support the conda installed version because it assumed the folder layout is standard.

**Comment by jrouly** [comment]
@cloudhan I think you're on the right track. Or at least, you put me on the right track with that pointer.

I found [this thread](https://github.com/conda/conda/issues/7757) describing similar issues in other tools (not Bazel) that require `CUDA_HOME` when CUDA is installed via Conda.

Turns out my problem was not having `cudatoolkit-dev` installed. I'm not entirely sure _what_ that provides, but it provides it in such a way as to satisfy `rules_cuda`'s expectations about where library files should reside.

For anyone who finds this thread:
```
conda install cudatoolkit-dev
```

should be all you need to make `rules_cuda` happy!
