### ISSUE TITLE
[BUG] compiling failed with nvcc+gcc using custom cc_toolchain with platform, with default cc_toolchain success.

### ISSUE THREAD

**Issue by ZhenshengLee** [bazel-contrib/rules_cuda#261]
### brief

**NOTE**: in the default platform, which is x86_64(k8) toolchain , the compile works.
I wonder if it's a bug or just a misconfiguration in the toolchain_config?

### environment

bazel: version7.0.2
cctoolchain: //bazel/toolchains/v5l (a custom cc toolchain for cross compile in aarch64, like https://github.com/f0rmiga/gcc-toolchain/blob/main/toolchain/cc_toolchain_config.bzl)

```sh
├── toolchains
│   └── v5l
│       ├── BUILD
│       ├── v5l.BUILD
│       └── v5l_cc_toolchain_config.bzl
```

### repro steps

simply compile the basic example with cu_library and report the following errors.
**NOTE**: in the default platform, which is x86_64(k8) toolchain , the compile works.

```sh
(09:38:08) ERROR: /gw_demo/modules/team_demo/module_demo/BUILD:46:13: Compiling modules/team_demo/module_demo/src/module_demo/module_cuda.cu failed: (Exit 1): nvcc failed: error executing CudaCompile command (from target //modules/team_demo/module_demo:module_cuda) 
  (cd /home/zs/.cache/bazel/_bazel_zs/2c098eac6c684e1fabebb74f5f4483bd/execroot/gaos && \
  exec env - \
    PATH=bazel/toolchains/v5l \
  /usr/local/cuda/bin/nvcc -x cu -gencode 'arch=compute_86,code=compute_86' -gencode 'arch=compute_86,code=sm_86' -Xcompiler -fPIC -ccbin bazel/toolchains/v5l/gcc -I . -I bazel-out/aarch64-dbg/bin -I external/local_cuda -I bazel-out/aarch64-dbg/bin/external/local_cuda -isystem modules/team_demo/module_demo/include -isystem bazel-out/aarch64-dbg/bin/modules/team_demo/module_demo/include -isystem external/local_cuda/cuda/include -isystem bazel-out/aarch64-dbg/bin/external/local_cuda/cuda/include -Xcompiler '--cbin /hhh' -O0 -g -c modules/team_demo/module_demo/src/module_demo/module_cuda.cu -o bazel-out/aarch64-dbg/bin/modules/team_demo/module_demo/_objs/module_cuda/module_cuda.pic.o --expt-relaxed-constexpr --extended-lambda)
# Configuration: 8d031e595766517cd77a614587e21bb1501021be933a2e40e13d75f49ba5eaf0
# Execution platform: @@local_config_platform//:host
bazel/toolchains/v5l/gcc: No such file or directory
nvcc fatal   : Failed to preprocess host compiler properties.
(09:38:08) INFO: Elapsed time: 0.480s, Critical Path: 0.03s
(09:38:08) INFO: 5 processes: 5 internal.
(09:38:08) ERROR: Build did NOT complete successfully
```

### considerations

`-ccbin` parameter is in https://github.com/bazel-contrib/rules_cuda/blob/13a6f1379ec128093edf8dc1f70ae5e5601f31f4/cuda/private/toolchain_configs/nvcc.bzl#L66-L78

which is created from `host_compiler`, in https://github.com/bazel-contrib/rules_cuda/blob/13a6f1379ec128093edf8dc1f70ae5e5601f31f4/cuda/private/actions/compile.bzl#L25-L37

originaly created from https://github.com/bazel-contrib/rules_cuda/blob/13a6f1379ec128093edf8dc1f70ae5e5601f31f4/cuda/private/rules/cuda_library.bzl#L9-L18

### related info

there is an issue https://github.com/bazelbuild/bazel/issues/22561 , which describes the `*_executable` variable empty, but I think this issue is not related here, because the variable compiler_executable is wrong with `bazel/toolchains/v5l`, the gcc toolchain and some other tools are linked under the wrong directory. actually the gcc is in `/drive/toolchains/aarch64--glibc--stable-2022.03-1/bin/aarch64-linux-gcc`

https://github.com/bazelbuild/bazel/issues/7105 this issue describes the `cc_toolchain.compiler_executable()` usage.

https://bazel.build/rules/lib/providers/CcToolchainInfo#compiler_executable and https://bazel.build/configure/integrate-cpp are the bazel official doc about this topic.

the official example about this variable is here https://github.com/bazelbuild/rules_cc/blob/main/examples/write_cc_toolchain_cpu/write_cc_toolchain_cpu.bzl

I wonder if it's a bug or just a misconfiguration in the toolchain_config?

### workaround(failed)

I tried to set some soft links to the toolchain crosstool, but failing with more compiling errors.

```sh
ln -s /drive/toolchains/aarch64--glibc--stable-2022.03-1/bin/aarch64-linux-gcc /gw_demo/bazel/toolchains/v5l/gcc
ln -s /drive/toolchains/aarch64--glibc--stable-2022.03-1/bin/aarch64-linux-gcc.br_real /gw_demo/bazel/toolchains/bin/gcc.br_real
```

**Comment by cloudhan** [comment]
Seems to be a hermatic issue on first glance (gcc executable is not correctly brought into the building sandbox). The ccbin is just taken from the cc toolchain in use and then passthrough, since cc_toolchain is an implicit dep, then all related files claimed by the cc toolchain config should be brought into the sandbox automatically. You might need to inspect into the `bazel-<your_repo>/external/local_config_cc` for the cc toolchain configuration.

Before dive deep, it is worth to first try to use `--spawn_strategy=local` with `bazel build` to see how it goes.

**Comment by ZhenshengLee** [comment]
BTW, is there any plan of the project give an example to use custom/crosscompile cc_toolchain?

**Comment by ZhenshengLee** [comment]
After add tool_paths in cc_toolchain_config_info, the variable gets available.

```bzl
tool_paths = [
        tool_path(
            name = "ld",
            path = DRIVE_SDK_V5L_TOOLCHAIN_ROOT + "/bin/aarch64-buildroot-linux-gnu-ld.gold",
        ),
        tool_path(
            name = "cpp",
            path = DRIVE_SDK_V5L_TOOLCHAIN_ROOT + "/bin/aarch64-buildroot-linux-gnu-cpp",
        ),
        tool_path(
            name = "dwp",
            path = DRIVE_SDK_V5L_TOOLCHAIN_ROOT + "/bin/aarch64-buildroot-linux-gnu-dwp",
        ),
        tool_path(
            name = "gcov",
            path = DRIVE_SDK_V5L_TOOLCHAIN_ROOT + "/bin/aarch64-buildroot-linux-gnu-gcov",
        ),
        tool_path(
            name = "nm",
            path = DRIVE_SDK_V5L_TOOLCHAIN_ROOT + "/bin/aarch64-buildroot-linux-gnu-nm",
        ),
        tool_path(
            name = "objcopy",
            path = DRIVE_SDK_V5L_TOOLCHAIN_ROOT + "/bin/aarch64-buildroot-linux-gnu-objcopy",
        ),
        tool_path(
            name = "objdump",
            path = DRIVE_SDK_V5L_TOOLCHAIN_ROOT + "/bin/aarch64-buildroot-linux-gnu-objdump",
        ),
        tool_path(
            name = "strip",
            path = DRIVE_SDK_V5L_TOOLCHAIN_ROOT + "/bin/aarch64-buildroot-linux-gnu-strip",
        ),
        tool_path(
            name = "gcc",
            path = DRIVE_SDK_V5L_TOOLCHAIN_ROOT + "/bin/aarch64-buildroot-linux-gnu-gcc",
        ),
        tool_path(
            name = "ar",
            path = DRIVE_SDK_V5L_TOOLCHAIN_ROOT + "/bin/aarch64-buildroot-linux-gnu-ar",
        ),
    ]
```

**Comment by hypdeb** [comment]
If it can help anyone finding this issue in the future: facing a similar issue using https://github.com/bazelbuild/rules_cc to declare my `cc_toolchain`. It seems that it does not correctly set whatever is returned by `cc_toolchain.compiler_executable`.

**Comment by hypdeb** [comment]
Digging a bit deeper, found that `cc_toolchain.compiler_executable` [is on its way out](https://github.com/bazelbuild/bazel/blob/master/site/en/configure/integrate-cpp.md#generating-command-lines-and-environment-variables-using-the-c-toolchain-generate-command-lines-toolchain). This means that the issue should be fixed here by using `get_tool_for_action` instead. I'll try to create a pull request.
