### ISSUE TITLE
Allow cc_toolchain injection for cuda_toolchain

### ISSUE THREAD

**Issue by hofbi** [bazel-contrib/rules_cuda#272]
[Here](https://github.com/bazel-contrib/rules_cuda/blob/main/cuda/private/toolchain.bzl#L38C10-L38C23) in the cuda_toolchain rule, you specify the `"_cc_toolchain": attr.label(default = "@bazel_tools//tools/cpp:current_cc_toolchain")`. I would like to specify a different cc toolchain. What I am currently at is

```
cuda_toolchain(
    name = "nvcc-local",
    compiler_executable = "path to my nvcc compiler",
    toolchain_config = ":my-nvcc-config",
    _cc_toolchian = ":my-cc-toolchain"  # <-- this one fails
)
```

Any idea what's wrong with my setup?

**Comment by cloudhan** [comment]
What is the error message?

**Comment by hofbi** [comment]
`no such attribute '_cc_toolchain' in 'cuda_toolchain' rule (did you mean '$cc_toolchain'?)`

**Comment by cloudhan** [comment]
https://bazel.build/extending/rules#private_attributes_and_implicit_dependencies

**Comment by cloudhan** [comment]
To allow some kind of customizaiton, we might instead of implement something like

https://github.com/bazelbuild/rules_python/blob/612baef1f14d1af89594f45559bc9c11a50d390a/python/BUILD.bazel#L340-L342

depends on something like `current_cuda_cc_toolchain`.

**Comment by cloudhan** [comment]
Related to #194

**Comment by hofbi** [comment]
Thanks, closing this as duplicate of #194
