### ISSUE TITLE
Need allow_empty=True for glob with Bazel 8

### ISSUE THREAD

**Issue by axbycc-mark** [bazel-contrib/rules_cuda#294]
In Bazel 8, glob's default [allow_empty is False](https://github.com/bazelbuild/bazel/issues/8195). This broke my build because some of the local_cuda's globs were empty. I manually fixed it in my local repo in two spots.
```
# local_cuda BUILD


filegroup(
    name = "compiler_deps",
    srcs = [
        ":_cuda_header_files",
    ] + glob([
        "cuda/version.txt",
        "cuda/version.json",
        "cuda/bin/**",
        "cuda/lib64/**",
        "cuda/nvvm/**",
    ], allow_empty=True),
)

...

cc_library(
    name = "cupti_headers",
    hdrs = glob(["cuda/extras/CUPTI/include/*.h"], allow_empty=True),
    includes = ["cuda/extras/CUPTI/include"],
)
```

**Comment by cloudhan** [comment]
Are you using an old release?

**Comment by axbycc-mark** [comment]
Ah, yes I assumed the version mentioned in the readme (0.2.1) was the latest. Upgrading to 0.2.3 fixes it. Thanks!
