### ISSUE TITLE
Are there plans to support NCCL local repository?

### ISSUE THREAD

**Issue by MoFHeka** [bazel-contrib/rules_cuda#307]
NCCL is usually installed along with CUDA as a base library, and it is convenient to have a rule.

**Comment by cloudhan** [comment]
See this example https://github.com/bazel-contrib/rules_cuda/tree/main/examples/nccl you can copy them to you repo.

**Comment by MoFHeka** [comment]
I mean find some possible path of installed nccl and import them just like cudatoolkit library.在 2024年12月31日，14:59，cloudhan ***@***.***> 写道：﻿
See this example https://github.com/bazel-contrib/rules_cuda/tree/main/examples/nccl you can copy them to you repo.

**Comment by cloudhan** [comment]
Nope, this repo will only include cudax library.

**Comment by MoFHeka** [comment]
A lite version of bazel local installed NCCL
https://github.com/MoFHeka/rules_nccl

**Comment by cloudhan** [comment]
I actually have some ideas on repo injection, for cudnn or nccl, etc. In currently wip hermetic toolchain, it is actually very easy to expose repo to targets mapping via a key-value pair in a dict. I might design some mechanism to customize the process for users to 
- inject a BUILD file to setup a repo
- map targets in that BUILD file to local_cuda repo.
