### ISSUE TITLE
 ccache: FATAL: Could not find compiler "gcc" in PATH #3642 

### ISSUE THREAD

**Issue by lehuyduc** [bazel-contrib/rules_cuda#67]
I've tested with bazel 4.2, 5.0, 6.0, and it all happens. So it's probably not related to bazel version.

I've tried
```
export CC="/usr/bin/gcc"
export CXX="/usr/bin/g++"
```
before running `bazel build my_project/...`, but it still has this error.
I've also tried `bazel build //your/build/target --action_env=PATH=$PATH`, same error.

I've checked and path to gcc is clearly in `$PATH`. What else might cause this problem ? Thanks.

**Comment by cloudhan** [comment]
The critical error message is missing. So I am just guessing.

First, on linux, bazel use sandbox by default. This means all unnecessary files (the rules defines what is necessary) are inaccessible from within the sandbox.

Second, based on `ccache` things, I'd guessing you installed it to `/usr/local/bin` and played around you `$PATH` for that purpose. IIRC, cc rules, also use some predefined template to configure toolchains to use those pathes.

rules_cuda simply depends on the cc_toolchain to work correctly. I am not sure if you are able to use `cc_library` rules or sth the like.

With your messy environment, that might have made the cc toolchain auto configuration step in some faulty state. You better 
- clean expunge, shutdown, rebuild with CC and CXX environment set
or
- find a clean environment to test it out.

**Comment by lehuyduc** [comment]
I'm not sure what was wrong. But I re-install everything and now it's suddenly correct. So I'll close the issue.

Thanks!
