### ISSUE TITLE
Support setting arbitrary `CUDA_NVCC_FLAGS`

### ISSUE THREAD

**Issue by hypdeb** [bazel-contrib/rules_cuda#86]
Hello,

I would like to pass some `CUDA_NVCC_FLAGS` to `nvcc` when using the rules you provide. How would I achieve this ? In particular I am interested in the `-allow-unsupported-compiler` flag. I tried using environment variables, both set in my `.bazelrc` file and through the command line, but it seems they do not make it through to the build.

**Comment by cloudhan** [comment]
Just `bazel build --@rules_cuda//cuda:copts=<all_your_flags> ...`, you can add this to your `.bazelrc`. But you should notice the bug [#84](https://togithub.com/bazel-contrib/rules_cuda/issues/84), before it is fixed, you can only use `--@rules_cuda//cuda:copts` at most once 😑.

**Comment by hypdeb** [comment]
That seems to work since I now get a different error :D I guess now I'm seeing the consequences of using an unsupported compiler.

Thanks for the quick answer!
